### ISSUE TITLE
Support better cache control (e.g. expiration date, force clean, ...)

### ISSUE THREAD

**Issue by brunolemos** [DylanVann/react-native-fast-image#137]
@DylanVann

I've read all issues on this repo related to cache. I know you usually reply with:
- "just use immutable url"
- "don't worry about the cache" (storage limit)
- "I don't think it's that important" (to control cache expiring)
- "It's like a first in first out buffer" 

I do use immutable images urls. It works great. For now.

But does it make sense for an app to keep storing images that will be used some more times in the short and mid term but probably not on the long term? Just waiting for the storage limit to come and without knowing for sure that it will keep working on all devices (specially androids)?

There are so many people asking for this feature:
- #16 How do i control cache expires?
- #24 Control cache time?
- #32 Add non-aggressive caching
- #63 How remove cached images?
- #93 Invalidate cache (etag)
- #114 programatically bust the cache on receiving low memory warning
- #134 Glide cache signature 
- #149 Cache is too resilient

Some people mentioned that the underlying libs does support cache control, so maybe it's just a matter of exposing their methods here.

Are you open for a pull request if some contributor decides to implement them?
Or you have really decided that this won't happen on this package?

**Comment by brunolemos** [comment]
I'm closing because there are other issues related.
But please reopen if you decide this repo would accept some more cache control features.

I'm personally in favor of a way to clean cache (per image or all) and to set an expire date (per image), but not in favor of etags of other header techniques, at least not for now.

**Comment by DylanVann** [comment]
I'm open to PRs that don't make things more complicated than they need to be.

The underlying libraries both set reasonable limits on the amount of data that will be cached. When the libraries fill up that data the oldest images are removed from the cache.

I'm sort of irritated by the issues because I feel like it's akin to asking for manual memory management in a garbage collected or reference counted language. It just isn't something you should need to do, and I'm not sure why people think they need to do it.

Being able to purge the in-memory cache on receiving a low memory warning is understandable, but controlling the long term caches really doesn't seem very necessary.

I'd rather have a few specific and actionable issues than one big "cache control" issue so I'm closing this in favour of those other issues you mentioned.
