### ISSUE TITLE
`React` pod dependency causes build to fail

### ISSUE THREAD

**Issue by oferRounds** [DylanVann/react-native-fast-image#174]
Getting:
```
... tries to require `react-native`, but there are several files providing this module. You can delete or fix them: 

  * `<project_path>/ios/Pods/React/package.json`
  * `<project_path>/node_modules/react-native/package.json`
```

Any workaround for this issue?

**Comment by oferRounds** [comment]
Also, when running `pod install` I get the message:
`[!] React has been deprecated`

**Comment by MacKentoch** [comment]
I followed example [here](https://github.com/DylanVann/react-native-fast-image/blob/master/ReactNativeFastImageCocoaPodsExample/ios/Podfile).

But no luck I have `FastImageView does not exists` when launching after pod update and caches reset:

```bash
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod update
```

**Comment by n1ru4l** [comment]
@oferRounds Can you show us your Podfile? You should set up your Podfile like in the example here: https://facebook.github.io/react-native/docs/integration-with-existing-apps.html

**Comment by oferRounds** [comment]
@MacKentoch  @n1ru4l – thanks!
I was eventually able to make it work using by following the example:

https://github.com/DylanVann/react-native-fast-image/blob/master/ReactNativeFastImageCocoaPodsExample/ios/Podfile

But it was very hard... Had a long struggle! :)

Using `React` has a pod dependency was the source of pain on my case

**Comment by n1ru4l** [comment]
Glad it worked! @oferRounds Could you please close this issue? 😇

**Comment by oferRounds** [comment]
Yes! THANK YOU!

**Comment by MacKentoch** [comment]
For history, **I fixed my issue** by manual linking `react-native-fast-image` (*since pod is a real mess with react-native but I need it for firebase...*).

After 
- deleting node_modules
- deleting ios/Pods
- then `npm install`
- manual linked the library (*to avoid react-link link to update podfile*)
- pod update with pod:

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'beewhizz' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for beewhizz
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Crash'
  pod 'Firebase/Messaging'
end

```
- then `pod update`

I had this issue like in [stack overflow](https://stackoverflow.com/questions/46767010/xcode-9-0-type-react-native-run-ios-run-failed)

To finally fix it I had to:
- delete `Developer/xcode/DereivedData`content
- clean ios project (*xcode clean project*)
- delete ios/build entire directory

NOW IT WORKS ✌️

**Comment by oferRounds** [comment]
@MacKentoch - awesome! Thanks for sharing!!!
