### ISSUE TITLE
View config not found 

### ISSUE THREAD

**Issue by pontusab** [DylanVann/react-native-fast-image#175]
<img width="429" alt="screen shot 2018-03-31 at 12 04 45" src="https://user-images.githubusercontent.com/655158/38162104-c87e6432-34db-11e8-8686-a4492bd38813.png">

```
"react": "^16.3.0",
"react-native": "0.54.4",
```

I get this error when running: 

`<FastImage source={{ uri }} resizeMode={FastImage.resizeMode.contain} />`

**Comment by csotiriou** [comment]
+1

**Comment by rayhk6** [comment]
+1

**Comment by anvu69** [comment]
+1

**Comment by uusa35** [comment]
i installed it using pod and it's working fine now.

**Comment by csotiriou** [comment]
Probably it's a linker error. I unlinked and linked the FastImage library in Xcode again, and it worked.

**Comment by pontusab** [comment]
So instead of running `react-native link` you can set up it manually for now to get it to work.

**Comment by newah** [comment]
getting this error, but only sometimes (ios). Seems to work fine. But in the release I keep seeing it from time to time. Sometimes during initial load of the app, but also happens when app is already loaded, using FastImage successfully and suddenly this happens (we get crash reports)

"react-native": "0.59.3",
"react-native-fast-image": "^5.2.0",
