### ISSUE TITLE
How can I use width and height from onLoad?

### ISSUE THREAD

**Issue by nica0012** [DylanVann/react-native-fast-image#198]
Whenever I try to use the width and height values from the onLoad callback by setting them in state, my component renders constantly. However when I console log the values they only happen once (which is what I expect when i set the values in state). I am trying to set my image height/width to be the real dimensions of the image with no delay.

Cheers

**Comment by DylanVann** [comment]
The reason `Image` requires a width and height in `style` is to prevent UI jank when an image is loaded in. So you generally want to decide on the size beforehand and then use `resizeMode` to crop the image.

There isn't a way to set the width and height to the actual width and height of the image through `onLoad` with no delay since they aren't known until the image is downloaded.

I'm not sure I understand what the problem is.

**Comment by nica0012** [comment]
@DylanVann Thanks for the quick response. So basically my problem is I want to be able to use the width and height to size my image with it's actual dimensions like getSize() from the Image component. Currently I am able to console.log the width and height correctly from the onLoad(), but I cant seem to store those values to be used. I tried to set a width and height piece of state with the values but it caused an infinite loop.

**Comment by nica0012** [comment]
I found what my issue was. I had my Image animating in from another component which for some reason was causing the infinite loop/not displaying anything. I removed the animation and everything now works as expected (Without animation of course).
