### ISSUE TITLE
Publish the last version in npm

### ISSUE THREAD

**Issue by lucasferreira** [DylanVann/react-native-fast-image#232]
Hi @DylanVann,

Thanks for this wonderful lib. Can you please publish the last version in npm for us?

I need the source.cache feature in my app, but in the actual version at npm it isn't possible to use this feature.

Thank you again ;)

**Comment by smadey** [comment]
+1

**Comment by niocncn** [comment]
+1

**Comment by n1ru4l** [comment]
@lucasferreira @smadey @niocncn In the meantime we can use `yarn add react-native-fast-image@https://github.com/DylanVann/react-native-fast-image.git#05830ad8a70f243dc4a6e089714866070f48f58a`

**Comment by NikoMontana** [comment]
+1

**Comment by tobi512** [comment]
Same problem here, we also need a new version with the included Glide-v4 (also opened an issue #259).

**Comment by NikoMontana** [comment]
The contributor put it also on npm, but did not update the readme.

https://www.npmjs.com/package/react-native-fast-image

**Comment by tobi512** [comment]
@NikoMontana We need a release of the current master-branch and a fix for the non-building Android part due to a wrong support library version declaration. Issue and PR for this already exist, see #259 (especially my second commend) and #261. 
Since we don't have time to wait for the release and PR merge, we published a fork on npm as v4.0.15 (https://www.npmjs.com/package/dm-react-native-fast-image) until it's officially fixed here.

Feel free to use our fork (no git submodule or build errors 🎉)...

**Comment by NikoMontana** [comment]
@tobi512 I cannot remember if this lib caused the build problem I have had once in a while or if it was because I upgraded react-native to 0.55 from 0.51. 

But I can remember that adding this: `android.enableAapt2=false` to the gradle.proporties was kind of an emergency solution. Anyway thank you for notifying me about your fork!

**Comment by DylanVann** [comment]
Sorry everyone, very busy with work and other projects.

If anyone is reading this: **watch out for the second system effect**. I've been trying to finish up way too much stuff to include in `react-native-fast-image@5.0.0`. I should have just kept publishing incremental versions off master instead.

I don't recall everything else I wanted to get done or fixed, but I did just publish master as `5.0.0`.
