### ISSUE TITLE
WebP not showing on iOS 12

### ISSUE THREAD

**Issue by liukaixin01** [DylanVann/react-native-fast-image#298]
"react": "16.5.0",
"react-native": "0.57.1",
"react-native-fast-image": "^5.0.10"

**Comment by sesam** [comment]
the link above gives this solution:

> By default, you get just Core, so if you need WebP, add it in your Podfile:
> `pod 'SDWebImage/WebP'`

**Comment by XHTeng** [comment]
> the link above gives this solution:
> 
> > By default, you get just Core, so if you need WebP, add it in your Podfile:
> > `pod 'SDWebImage/WebP'`

That will report duplicate references `SDWebImage ` errors . Is there any solution?

**Comment by tjbenton** [comment]
I'm having the same issue on iOS, currently I can get alpha webp images(Lossless) to display, but not the solid ones(Lossy). Before attempting to switch to using this library we were using [`react-native-webp-support`](https://github.com/TGPSKI/react-native-webp-support) and both types of images were displaying correctly.
Here's a screenshot of it using that library and the default react-native `Image` component. I set the background color of the images to be gray so you could see that they were transparent
![screen shot 2018-12-18 at 2 34 46 pm](https://user-images.githubusercontent.com/4776422/50178595-f9de6480-02d2-11e9-888c-10c10adf02ce.png)


After attempting to switch to use this library the 1 image that wasn't transparent no longer loads.
![screen shot 2018-12-18 at 2 29 05 pm](https://user-images.githubusercontent.com/4776422/50178606-ffd44580-02d2-11e9-91c9-c8bb1b166221.png)

```
"react": "16.6.3",
"react-native": "0.57.7",
"react-native-fast-image": "5.1.1",
```

**Comment by ds8k** [comment]
@radeno @sesam This causes duplicate symbol errors

**Comment by sesam** [comment]
@ds8k @XHTeng you should replace `pod 'SDWebImage'` with `pod 'SDWebImage/WebP'`, or if you need also GIF or MapKit support then use the other syntax that is something like `, subspecs: ["Core", "WebP", "MapKit"]`
I'm not sure, but it might be that you have to change the code under node_modules/react-native-fast-image just to verify it can work (though hacky and unsustainable), then once we have a tested working correction then we can submot a PR so that DylanVann can release an update.

**Comment by DylanVann** [comment]
Fixed in the latest release! https://github.com/DylanVann/react-native-fast-image/releases/tag/v5.1.3
