### ISSUE TITLE
Android App crashes on startup.

### ISSUE THREAD

**Issue by manujbahl** [DylanVann/react-native-fast-image#516]
**Describe the bug**
Android app crashes as soon as it starts 
Happens on android only (iOS works fine)
I already added the excludeAppGlideModule but it did not help

**To Reproduce**
Steps to reproduce the behavior if possible, or a link to a reproduction repo:
1. App start using fast-image (v 5.2.0)

**Expected behavior**
App works fine.

**Screenshots**
Here is the error I am getting.

 java.lang.NoSuchMethodError: No super method apply(Lcom/bumptech/glide/request/RequestOptions;)Lcom/bumptech/glide/request/RequestOptions; in class Lcom/bumptech/glide/request/RequestOptions; or its super classes (declaration of 'com.bumptech.glide.request.RequestOptions' appears in /data/app/io.apptivate.apptivate-QzwpZ9CJ3LrnK8LnR2x3ZA==/base.apk)
        at com.dylanvann.fastimage.GlideOptions.apply(GlideOptions.java:605)
        at com.dylanvann.fastimage.GlideRequests.setRequestOptions(GlideRequests.java:170)
        at com.bumptech.glide.RequestManager.<init>(RequestManager.java:136)
        at com.bumptech.glide.RequestManager.<init>(RequestManager.java:94)
        at com.dylanvann.fastimage.GlideRequests.<init>(GlideRequests.java:38)
        at com.bumptech.glide.GeneratedRequestManagerFactory.build(GeneratedRequestManagerFactory.java:19)
        at com.bumptech.glide.manager.RequestManagerRetriever.fragmentGet(RequestManagerRetriever.java:388)
        at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:159)
        at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:118)
        at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:120)
        at com.bumptech.glide.Glide.with(Glide.java:716)
        at com.dylanvann.fastimage.FastImageViewManager.createViewInstance(FastImageViewManager.java:49)
        at com.dylanvann.fastimage.FastImageViewManager.createViewInstance(FastImageViewManager.java:31)

**Dependency versions**

- React Native version: 0.57.1 
- React version:
- React Native Fast Image version:  5.2.0

**Note:** if these are not the latest versions of each I recommend updating as extra effort will not be taken to be backwards compatible, and updating might resolving your issue.

**Comment by manujbahl** [comment]
Update. I had put the excludeAppGlideModule in the wrong place. After fixing that I am getting a different error.


![image](https://user-images.githubusercontent.com/5688107/60761639-7f242f00-a001-11e9-94f6-9c004c990c4d.png)

**Comment by NiciusB** [comment]
Exact same thing here.
I might have done something wrong, tho. Since I didn't have a `project` tag, I added `excludeAppGlideModule` inside `buildscript {
ext {
}
}`

**Comment by px-amaac** [comment]
Recently had to upgrade RN version to 59.9 and Glide with it. Currently getting this issue with diskCacheStrategy method missing using Glide 4.9.0 and Fast Image 6.1.1. Did not use 7.0 because not migrated to AndroidX yet. Previously this was working on RN 58.3, Glide 4.7.1, FastImage 5.2.0 with excludeAppGlideModule defined in project level build.gradle file like this.

```
project.ext {
    excludeAppGlideModule = true
}

buildscript { } 
```

I tried downgrading fast image but could not find a version that works.
I tried downgrading glide to 4.7.1 also tried 4.8.0 but again could not find a version combination that works.

**Comment by WrathChaos** [comment]
Related issue #484, still could not solve this issue :( @DylanVann

**Comment by px-amaac** [comment]
> Related issue #27, still could not solve this issue :( @DylanVann

I do not see how this is related at all. Could you elaborate? 
I looked through #27 and could not find a single consistent stack trace. I am not sure that everyone there has the same problem. It seems `Error while updating property 'source' of a view managed by: FastImageView` is a common base error for failures in this library. This error is related to missing generated methods for Request Options.[ I am guessing its caused by this pr](https://github.com/bumptech/glide/commit/ed20643fb94d4e17f4cdb3699a6d83621408dd34) from glide as it warns of breaking changes to subclasses of request options. 

I commented out[ this line](https://github.com/DylanVann/react-native-fast-image/blob/5f653838b853f115777b1a2394238e5b3698feda/android/src/main/java/com/dylanvann/fastimage/FastImageViewConverter.java#L110) in FastImageViewConverter and the error defaults to the next request option. I am guessing this is not the way to build request options any more but Glide docs still use this process. Maybe this is more related to generated code from glide not working correctly.

Major problem is that I cannot downgrade to any other glide version and get a successful build for android. 

This error did not require an upgrade of fast image. The Glide upgrade is what caused this.

**Comment by px-amaac** [comment]
UPDATE: I managed to get our implementation to work. We are not able to upgrade to most recent version of this library(7.0.0) because we are not ready to migrate to AndroidX so we are still on 5.2.0 but this error was happening on 6.1.1 as well. Mainly this error was happening using Glide 4.9.0. We could not downgrade to Glide 4.7.1 because Android builds were failing due to upgrade to target 28 for 64-bit support.

Prior to Fast Image 7.0.0 the library was [defaulting its Glide version to 4.7.1](https://github.com/DylanVann/react-native-fast-image/blob/master/android/build.gradle#L19)

Fix that prevents runtime errors is to add the correct glideVersion to our project level build.gradle file.

```
project.ext {
    excludeAppGlideModule = true
    glideVersion = "4.9.0"
}

buildscript {}
```

Good luck. Happy coding.

**Comment by DylanVann** [comment]
This will need to wait until Expo updates to React Native 0.60.0.

**Comment by HankinsPan** [comment]
> UPDATE: I managed to get our implementation to work. We are not able to upgrade to most recent version of this library(7.0.0) because we are not ready to migrate to AndroidX so we are still on 5.2.0 but this error was happening on 6.1.1 as well. Mainly this error was happening using Glide 4.9.0. We could not downgrade to Glide 4.7.1 because Android builds were failing due to upgrade to target 28 for 64-bit support.
> 
> Prior to Fast Image 7.0.0 the library was [defaulting its Glide version to 4.7.1](https://github.com/DylanVann/react-native-fast-image/blob/master/android/build.gradle#L19)
> 
> Fix that prevents runtime errors is to add the correct glideVersion to our project level build.gradle file.
> 
> ```
> project.ext {
>     excludeAppGlideModule = true
>     glideVersion = "4.9.0"
> }
> 
> buildscript {}
> ```
> 
> Good luck. Happy coding.

Thank you very much, it solved my big problem
