### ISSUE TITLE
How preload works?

### ISSUE THREAD

**Issue by liqueflies** [DylanVann/react-native-fast-image#54]
Hi,
first of all thank you for your work.

Just a question, how preload works?

I've a collection of images, I have to prefetch all of them before render the component but I don't have callbacks, and I don't have Idea why in examples, image have token key inside headers and in preload there is authentication key, why I have to use them? and finally why you never used preloaded images?

I hope you can help to clarify me, thank you.

**Comment by althurzard** [comment]
Same. There isnt example for this feature. o_o

**Comment by ggepenyan** [comment]
Same here

**Comment by ggepenyan** [comment]
@DylanVann Why don't you answer any question. There is more than 40 issues ))

**Comment by DylanVann** [comment]
@ggepenyan New job, really busy. I know it sucks when maintainers are unavailable, but there's always forking. 🍴 

There is an example of preloading here:
https://github.com/DylanVann/react-native-fast-image/blob/master/example/FastImageExample.js#L68

- If your images do not require any headers to fetch them you don't have to send any headers.
- There's currently no callback implemented.
- It would probably be better to just render your images instead of trying to wait for them all to load first.

**Comment by emadbaqeri** [comment]
> @ggepenyan New job, really busy. I know it sucks when maintainers are unavailable, but there's always forking. 🍴
> 
> There is an example of preloading here: [https://github.com/DylanVann/react-native-fast-image/blob/master/example/FastImageExample.js#L68](https://github.com/DylanVann/react-native-fast-image/blob/master/example/FastImageExample.js?rgh-link-date=2017-11-06T04%3A11%3A18Z#L68)
> 
> * If your images do not require any headers to fetch them you don't have to send any headers.
> * There's currently no callback implemented.
> * It would probably be better to just render your images instead of trying to wait for them all to load first.

The link you have mentioned here is not working, can you provide a working example around this one?
