### ISSUE TITLE
New image on server

### ISSUE THREAD

**Issue by Waltari10** [DylanVann/react-native-fast-image#93]
Hey,

Thank you for the awesome package! My question is if I download an image from an url, and it changes, does FastImage download the new picture or keep displaying the old one? How does FastImage tell if an image from an URL has changed?

Thanks!

**Comment by lashae** [comment]
Let me add to @Waltari10: If the server returns `Etag` headers like AWS S3 does, does this package detect etag cache and invalidate the cache Image?

**Comment by DylanVann** [comment]
No it doesn't, it works like the libraries it's based on (SDWebImage and Glide) do. If it caches an image for a url it is assumed that image will not change.

I've added some documentation on how caching is handled: https://github.com/DylanVann/react-native-fast-image/blob/8aa6c6bc13ae48d3116ab19ddb4947ad108ae964/docs/how-is-caching-handled.md

In the future other modes may be added to respect those headers.

**Comment by lashae** [comment]
Thanks. This is a very important feature in deed, since we couldn't find any library we had to implement it in our codebase. Hope you add this to your roadmap ;-)

**Comment by DylanVann** [comment]
I don't think it's that important. Immutable image urls are a better practice for creating your API. You can definitely store images with immutable urls on S3.

If this component is to be a full replacement for `Image` though I'll have to add support for other cache policies at some point. Not looking forward to it, especially since other cache policies aren't best practices anyways.

**Comment by bansal-rahul** [comment]
@DylanVann 
Can you please clarify meaning of "immutable" url? I mean when does a url is considered to be changed. For eg. is url considered to be changed if its query params change?
